# Generated by Django 5.2.11 on 2026-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_recipe_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Price"
            ),
        ),
    ]
