# Generated by Django 5.2.11 on 2026-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tag_recipe_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
    ]
