# Generated by Django 5.2.12 on 2026-03-09 03:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_tag_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="",
                upload_to=core.models.recipe_image_file_path,
                verbose_name="Image",
            ),
            preserve_default=False,
        ),
    ]
