# Generated by Django 5.2.12 on 2026-03-09 12:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=core.models.recipe_image_file_path,
                verbose_name="Image",
            ),
        ),
    ]
