# Generated by Django 5.2.11 on 2026-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Link"),
        ),
    ]
