# Generated by Django 5.2.11 on 2026-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ingredient_tag_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                to="core.ingredient", verbose_name="Ingredients"
            ),
        ),
    ]
